### ISSUE TITLE
sklearn problem

### ISSUE THREAD

**Issue by yiming-lzx** [DataCanvasIO/Cooka#8]
Send train process event: 
http://localhost:8000/api/dataset/iris_test_1/feature-series/default/train-job/train_job_iris_test_1_HyperGBM_20220705134148885806
{"type": "optimize", "status": "succeed", "took": 0.16978836059570312, "datetime": 1656999719237, "extension": {"trial_no": 10, "status": "succeed", "extension": {"reward": 3.8680241084247187, "elapsed": 0.16978836059570312, "params": {"missing": NaN, "reg_alpha": 0.01, "learning_rate": 0.001, "missing_values": NaN, "n_estimators": 200, "hp_or": 0, "reg_lambda": 0.01, "max_depth": 5, "hp_lazy": 0}}}}
07-05 13:41:59 I hypernets.c.callbacks.py 196 - trial end. reward:3.8680241084247187, improved:False, elapsed:0.16978836059570312
07-05 13:41:59 I hypernets.c.callbacks.py 197 - Total elapsed:3.091360569000244
07-05 13:41:59 I hypernets.c.callbacks.py 99 - Early stopping on trial : 10, best reward: 0.32170346973301056, best_trial: 5
07-05 13:41:59 I hypergbm.experiment.py 837 - fit_transform final_ensemble
07-05 13:41:59 E hypernets.e._experiment.py 85 - ExperiementID:[None] - ensemble: Unknown label type: (68     6.2
31     5.4
107    7.3
25     5.0
12     4.8
133    6.3
17     5.1
111    6.4
79     5.7
129    7.2
35     5.0
105    7.6
18     5.7
57     4.9
27     5.2
Name: __tabular-toolbox__Y__, dtype: float64,)
Traceback (most recent call last):
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/hypernets/experiment/_experiment.py", line 75, in run
    y_eval=self.y_eval, eval_size=self.eval_size, **kwargs)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/hypergbm/experiment.py", line 1116, in train
    return super().train(hyper_model, X_train, y_train, X_test, X_eval, y_eval, **kwargs)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/hypergbm/experiment.py", line 839, in train
    step.fit_transform(hyper_model, X_train, y_train, X_test=X_test, X_eval=X_eval, y_eval=y_eval, **kwargs)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/hypergbm/experiment.py", line 549, in fit_transform
    ensemble.fit(X_eval, y_eval)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/tabular_toolbox/ensemble/base_ensemble.py", line 85, in fit
    self.fit_predictions(est_predictions, y)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/tabular_toolbox/ensemble/voting.py", line 106, in fit_predictions
    score = self.scorer._score_func(y_true, mean_predictions, **self.scorer._kwargs) * self.scorer._sign
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 2237, in log_loss
    lb.fit(y_true)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/preprocessing/_label.py", line 297, in fit
    self.classes_ = unique_labels(y)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 98, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (68     6.2
31     5.4
107    7.3
25     5.0
12     4.8
133    6.3
17     5.1
111    6.4
79     5.7
129    7.2
35     5.0
105    7.6
18     5.7
57     4.9
27     5.2
Name: __tabular-toolbox__Y__, dtype: float64,)
[13:41:59] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[13:41:59] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[13:41:59] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Send train process event: 
http://localhost:8000/api/dataset/iris_test_1/feature-series/default/train-job/train_job_iris_test_1_HyperGBM_20220705134148885806
{"type": "searched", "status": "succeed", "took": 3.3770127296447754, "datetime": 1656999719469, "extension": null}
Send train process event: 
http://localhost:8000/api/dataset/iris_test_1/feature-series/default/train-job/train_job_iris_test_1_HyperGBM_20220705134148885806
{"type": "evaluate", "status": "failed", "took": 2.5987625122070312e-05, "datetime": 1656999719487, "extension": {}}
Traceback (most recent call last):
  File "/root/cooka/dataset/iris_test_1/experiments/iris_test_1_2/train.py", line 285, in 
    raise e
  File "/root/cooka/dataset/iris_test_1/experiments/iris_test_1_2/train.py", line 253, in 
    y_pred = estimator.predict(X_test)
AttributeError: 'NoneType' object has no attribute 'predict'

pip install cooka= 0.1.5
I have try sklean==0.23.1/0.24.2/1.0.0/1.0.5
but it is not work.
all regression task report the same problem
谢谢

**Comment by oaksharks** [comment]
Hi yiming-lzx, 
 it seems that cooka recognizes it as a multi-classification task,
please set the task type to regression on the training page and try again .

**Comment by yiming-lzx** [comment]
> Hi yiming-lzx, it seems that cooka recognizes it as a multi-classification task, please set the task type to regression on the training page and try again .


not the type of task, when i upgrade deeptables==0.1.13, hypergbm==0.2.3, it works fine.

**Comment by yiming-lzx** [comment]
> Hi yiming-lzx, it seems that cooka recognizes it as a multi-classification task, please set the task type to regression on the training page and try again .


not the type of task, when i upgrade deeptables==0.1.13, hypergbm==0.2.3, it works fine.
